# this file is adapted from:
# https://github.com/joeynmt/joeynmt/blob/master/configs/iwslt14_deen_bpe.yaml

name: "rnn_wmt16_factors_deen"

data:
    src: "de"
    trg: "en"
    train: "data/train.bpe"
    dev:   "data/dev.bpe"
    test:  "data/test.bpe"
    level: "bpe"
    lowercase: False
    max_sent_length: 80
    src_vocab: "shared_models/vocab.txt"
    trg_vocab: "shared_models/vocab.txt"
    # changes for factors:
    # factor_vocab: "shared_models/vocab.factor"
    # factor_voc_limit: 1000
    # factor_voc_min_freq: 1
    # factor_combine: "add", # or: "concatenate"
    # use_factor: True

testing:
    beam_size: 5
    alpha: 1.0

training:
    optimizer: "adam"
    normalization: "tokens"
    learning_rate: 0.0002
    batch_size: 80
    scheduling: "plateau"
    patience: 8
    weight_decay: 0.0
    decrease_factor: 0.7
    early_stopping_metric: "ppl"
    epochs: 100
    validation_freq: 500
    logging_freq: 100
    eval_metric: "bleu"
    model_dir: "models/rnn_wmt16_factors_deen"
    overwrite: False
    shuffle: True
    use_cuda: False
    max_output_length: 80
    print_valid_sents: [0, 1, 2, 3, 4]

model:
    tied_embeddings: True
    tied_softmax: True
    encoder:
        rnn_type: "gru"
        # changes for factors:
        #factor_embeddings:
        #    embedding_dim: 16
        #    scale: False
        embeddings:
            embedding_dim: 512
            scale: False
        hidden_size: 512
        bidirectional: True
        dropout: 0.3
        num_layers: 1
    decoder:
        rnn_type: "gru"
        embeddings:
            embedding_dim: 512
            scale: False
        emb_scale: False
        hidden_size: 512
        dropout: 0.3
        hidden_dropout: 0.5
        num_layers: 1
        input_feeding: True
        init_hidden: "bridge"
        attention: "bahdanau"
